name: Node CI

on:
  push:
    branches: master

jobs:
  test:
    runs-on: ubuntu-18.04

    strategy:
      matrix:
        node-version: [10.x, 12.x, 13.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Rename config example to config.json
        run: mv "config.example.json" "config.json"
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install
        uses: ianwalter/puppeteer@v2.0.0
        with:
          args: yarn
      - name: npm install, build, and test
        run: |
          npm ci
          npm test
        env:
          CI: true
